name: Docs Build & Deploy
on:
  push:
    paths:
      - docs/**
      - package-lock.json
      - .github/workflows/docs.yml
jobs:
  Build-And-Deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: apt install -y curl git
      - run: . $HOME/.asdf/asdf.sh
      - run: apt install dirmngr gpg curl gawk
      - run: asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
      - run: asdf install nodejs latest
      - run: asdf local nodejs latest
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn docs:dev
      - run: rsync --progress --archive --compress --delete docs/.vuepress/dist/ /home/james/Development/www/public/rune
