name: Docs Build & Deploy
on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - package-lock.json
      - .github/workflows/docs.yml
      - tests/test_quick_start.lua
jobs:
  Build-And-Deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          apt install -y curl git
          apt install -y dirmngr gpg curl gawk
          git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.2 2>/dev/null
          . $HOME/.asdf/asdf.sh
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git 2>/dev/null
          asdf install nodejs latest
          asdf local nodejs latest
          npm install --global yarn
          yarn install
          yarn docs:build
          rsync --progress --archive --compress --delete docs/.vuepress/dist/ /home/james/Development/www/public/rune
