name: Docs Build & Deploy
on:
  push:
    paths:
      - docs/**
      - package-lock.json
      - .github/workflows/docs.yml
jobs:
  Build-And-Deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          apt install -y curl git
          . $HOME/.asdf/asdf.sh
          apt install -y dirmngr gpg curl gawk
          asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
          asdf install nodejs latest
          asdf local nodejs latest
          npm install --global yarn
          yarn install
          yarn docs:dev
          rsync --progress --archive --compress --delete docs/.vuepress/dist/ /home/james/Development/www/public/rune
